export const FETCH_PARAGRAPHS = 'FETCH_PARAGRAPHS';
export const FETCH_PARAGRAPHS_SUCCESS = 'FETCH_PARAGRAPHS_SUCCESS';
export const FETCH_PARAGRAPHS_FAILURE = 'FETCH_PARAGRAPHS_FAILURE';

export const URL_VALIDATION_FAILURE = 'URL_VALIDATION_FAILURE';

export const ADD_USER_SUGGESTION = 'ADD_USER_SUGGESTION';
export const ADD_USER_SUGGESTION_SUCCESS = 'ADD_USER_SUGGESTION_SUCCESS';
export const ADD_USER_SUGGESTION_FAILURE = 'ADD_USER_SUGGESTION_FAILURE';

export const APPROVE_SUGGESTION = 'APPROVE_SUGGESTION';

export const DELETE_PARAGRAPH_SUGGESTIONS = 'DELETE_PARAGRAPH_SUGGESTIONS';
